### ISSUE TITLE
🐛 Bug report: keyNotFound

### ISSUE THREAD

**Issue by jerryga** [StanfordBDHG/HealthGPT#32] opened 2023-07-06 10:30 UTC
### Description

keyNotFound(CodingKeys(stringValue: "id", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").", underlyingError: nil))

### Reproduction

Run-> Tap message

### Expected behavior

Receive correct response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment] 2023-07-06 16:17
Duplicate of https://github.com/StanfordBDHG/HealthGPT/issues/30 and addressed with #28 and #31 👍

**Closed by PSchmiedmayer** 2023-07-06 16:17 UTC
Labels: duplicate
